name: Deploy to EC2

on:
  push:
    branches:
      - main  # Cambia si usas otra rama como principal.

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Usa una versión específica de Ubuntu.

    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar conexión SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # 3. Desplegar en la instancia EC2
    - name: Deploy to EC2
      run: |
        echo "Conectándose a la instancia EC2..."
        ssh -o StrictHostKeyChecking=no ec2-user@3.80.221.241 << 'EOF'
        echo "Conexión SSH establecida."
        
        # Verificar si ya existe el repositorio y actualizarlo o clonarlo
        cd /home/ec2-user
        if [ -d "myProject-Actions" ]; then
          echo "Repositorio ya existe, actualizando..."
          cd myProject-Actions && git pull
        else
          echo "Clonando repositorio..."
          git clone https://github.com/SJaa2610/myProject-Actions.git
        fi
        
        echo "Deteniendo y eliminando contenedores existentes si los hay..."
        # Detener y eliminar contenedores si existen
        CONTAINERS=$(docker ps -q)
        if [ -n "$CONTAINERS" ]; then
          docker stop $CONTAINERS
          docker rm $CONTAINERS
        fi

        echo "Desplegando aplicación..."
        cd myProject-Actions
        docker-compose up -d
        echo "Despliegue completado."
        EOF

