name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.80.221.241 << 'EOF'
        # Navegar al directorio del proyecto
        cd /home/ec2-user/myProject-Actions
        
        # Asegurarse de estar en la rama main y obtener los últimos cambios
        git checkout main
        git fetch origin main
        git reset --hard origin/main
        
        # Reconstruir las imágenes Docker
        docker-compose down
        docker-compose build --no-cache
        docker-compose up -d
        
        # Limpiar imágenes huérfanas
        docker image prune -f
        
        echo "Despliegue completado exitosamente."
        EOF
